### ISSUE TITLE
Minor change to example file

### ISSUE THREAD

**Issue by muscatelle** [alextaujenis/RBD_SerialManager#1]
Thanks for this very handy piece of code.

Only a minor issue is that I found no defaults  and had to specify the flag and delimiter in your basic_serial_protocol example.
ie: 
   serial_manager.start();
  serial_manager.setFlag(10);
  serial_manager.setDelimiter(46);

Perhaps this was lost from the constructor or start() at some point.

**Comment by alextaujenis** [comment]
The default values are set in the header:

``` arduino
char _flag      = '\n';
char _delimiter = ',';
```

This library has been tested by compiling with the [arduino.cc](http://arduino.cc) IDE. What IDE are you compiling your sketches with? If you don't call setFlag() or setDelimiter(), does the library work?
