### ISSUE TITLE
SoftSerial & multiSerial suport?

### ISSUE THREAD

**Issue by zixzixzix** [alextaujenis/RBD_SerialManager#2]
Arduino mega 2560 has 4 Serialport.
How can i use them all?
And how to use solfserial in this library ?

**Comment by alextaujenis** [comment]
At this point RBD_SerialManager only works with the main serial port on pins 0 and 1, which is connected to the UART chip.

This library is still in alpha, which means I know some things are missing and the public interface is likely to change. Adding support for more than one serial port would be great. I don't have this immediately on my roadmap, but would likely accept a pull-request with this functionality.
